packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vite-plus: 0.3.3
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.3"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.3"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.3"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.3"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.3"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.3"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.3"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.3"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.3"
  - vite-plus@0.3.3
allowBuilds:
  electron: true
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
